name: Enforce PR Title Contains Jira Key 

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  enforce-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Check PR Title
        id: check_title
        run: |
          # Regex pattern for Jira keys (e.g., ABC-123)
          jira_pattern='[A-Z]+-[0-9]+'
          
          # PR title
          pr_title="${{ github.event.pull_request.title }}"

          # Check if the PR title matches the Jira key pattern or contains "merge"
          if [[ "$pr_title" =~ $jira_pattern ]] || [[ "$pr_title" =~ [Mm]erge ]]; then
            echo "PR title is valid."
          else
            echo "Error: PR title must contain a Jira key or the word 'merge'."
            exit 1
          fi
