name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  add_branch_prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          branchName=$(echo "${GITHUB_REF#refs/heads/}")
          branchPrefix=$(echo "$branchName" | awk -F'-' '{ for (i=1; i<NF; i++) printf "%s%s", $i, (i<NF-1 ? "-" : ""); }')
          echo "::set-output name=branch_prefix::$branchPrefix"

      - name: Update PR Description
        run: |
          branchPrefix="${{ steps.extract_branch_name.outputs.branch_prefix }}"
          prNumber=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          description=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
          updatedDescription="${description%\"}\n\n**Branch Prefix:** ${branchPrefix}\""

          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$updatedDescription\"}" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/pulls/$prNumber"
