name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  parse_jira_story_number:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Story Number
        id: extract_jira_story_number
        run: |
          # Get the branch name
          branch_name=$(echo "${{ github.head_ref }}")
          echo "Branch Name: $branch_name"

          # Extract Jira story number using regex
          if [[ $branch_name =~ ([^-]+-[^-]+) ]]; then
            jira_story_number="${BASH_REMATCH[1]}"
            echo "Jira Story Number: $jira_story_number"
          else
            echo "Jira story number not found in branch name"
            exit 1
          fi

          echo "::set-output name=jira_story_number::$jira_story_number"

      - name: Update PR Description
        if: success()
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.pull_request.number;
            const newDescription = `New description with Jira Story Number: ${context.payload.inputs.jira_story_number}`;
            github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: newDescription
            });
            inputs:
            jira_story_number: ${{ steps.extract_jira_story_number.outputs.jira_story_number }}

