name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  add_branch_prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          # Get the branch name
          branch_name=$(echo "${GITHUB_REF#refs/heads/}")

          # Split the branch name by the '-' delimiter
          IFS='-' read -ra branch_parts <<< "$branch_name"

          # Get the index of the last element
          last_index=$((${#branch_parts[@]} - 1))

          # Construct the branch prefix by joining the array elements before the last '-'
          branch_prefix="${branch_parts[@]:0:$last_index}"

          echo "::set-output name=branch_prefix::$branch_prefix"

      - name: Update PR Description
        run: |
          # Get the branch prefix from the previous step
          branch_prefix="${{ steps.extract_branch_name.outputs.branch_prefix }}"

          # Get the pull request number
          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")

          # Get the current description of the pull request
          description=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")

          # Append the branch prefix to the description
          updated_description="$description\n\n**Branch Prefix:** $branch_prefix"

          # Update the pull request description using GitHub API
          curl -X PATCH \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$updated_description\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"
