name: Add deploy URL to PR description

on:
  pull_request:

jobs:
  add_deploy_url:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Add deploy URL to PR description
        uses: chabroA/action-append-pr-description@master
        with:
          auth: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.event.repository.name }}
          owner: ${{ github.repository_owner }}
          pr: ${{ github.event.number }}
          url: "https://my-url.test"
          message: "My url :"

