name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  parse_jira_story_number:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Story Number
        id: extract_jira_story_number
        run: |
          # Get the branch name
          branch_name=$(echo "${{ github.head_ref }}")
          echo "Branch Name: $branch_name"

          # Extract Jira story number using regex
          if [[ $branch_name =~ ([^-]+-[^-]+) ]]; then
            jira_story_number="${BASH_REMATCH[1]}"
            echo "Jira Story Number: $jira_story_number"
          else
            echo "Jira story number not found in branch name"
            exit 1
          fi

          echo "::set-output name=jira_story_number::$jira_story_number"

      - name: Append Jira Story Number to PR Description
        if: steps.extract_jira_story_number.outputs.jira_story_number != ''
        run: |
          echo "Running the step"
          jira_story_number="${{ steps.extract_jira_story_number.outputs.jira_story_number }}"
          pr_number=$(jq -r '.pull_request.number' "$GITHUB_EVENT_PATH")
          current_description=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")

          updated_description="${current_description%\"}\n\n**Jira Story Number:** $jira_story_number\""
          echo "Updated Description: $updated_description"

          curl -X PATCH \
            -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"$updated_description\"}" \
            "https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number"
