name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  add_branch_prefix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Extract Branch Name
        id: extract_branch_name
        run: |
          const fs = require('fs');
          const branchName = process.env.GITHUB_REF.replace('refs/heads/', '');
          const branchParts = branchName.split('-');
          const branchPrefix = branchParts.slice(0, -1).join('-');
          console.log(`::set-output name=branch_prefix::${branchPrefix}`);

      - name: Update PR Description
        run: |
          const fs = require('fs');
          const branchPrefix = process.env.branch_prefix;
          const prNumber = JSON.parse(fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8')).pull_request.number;
          const description = fs.readFileSync(process.env.GITHUB_EVENT_PATH, 'utf8');
          const updatedDescription = `${description.trim()}\n\n**Branch Prefix:** ${branchPrefix}`;

          const { Octokit } = require("@octokit/core");
          const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });
          await octokit.request('PATCH /repos/{owner}/{repo}/pulls/{pull_number}', {
            owner: process.env.GITHUB_REPOSITORY.split('/')[0],
            repo: process.env.GITHUB_REPOSITORY.split('/')[1],
            pull_number: prNumber,
            body: updatedDescription
          });
