name: Add Branch Prefix to PR Description

on:
  pull_request:

jobs:
  parse_jira_story_number:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Jira Story Number
        id: extract_jira_story_number
        run: |
          # Get the branch name
          branch_name=$(echo "${{ github.head_ref }}")
          echo "Branch Name: $branch_name"

          # Extract Jira story number using regex
           if [[ $branch_name =~ ([^-]+-[^-]+) ]]; then
            jira_story_number="${BASH_REMATCH[1]}"
            echo "Jira Story Number: $jira_story_number"
          else
            echo "Jira story number not found in branch name"
            exit 1
          fi

          echo "::set-output name=jira_story_number::$jira_story_number"

      - name: Append Jira Story Number to PR Description
        if: steps.extract_branch_name.outputs.jira_story_number != ''
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.log('Starting script...');
            const prNumber = context.payload.pull_request.number;
            console.log('PR Number:', prNumber);
            const currentDescription = context.payload.pull_request.body;
            console.log('Current Description:', currentDescription);
            const jiraStoryNumber = '${{ steps.extract_branch_name.outputs.jira_story_number }}';
            console.log('Extracted Jira Story Number:', jiraStoryNumber);
            const updatedDescription = `${currentDescription}\n\n**Jira Story Number:** ${jiraStoryNumber}`;
            console.log('Updated Description:', updatedDescription);
            await github.pulls.update({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              body: updatedDescription
            });
            console.log('Description updated successfully.');
