name: Prepend JIRA Ticket to PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitHub CLI
        run: |
          # Install GitHub CLI
          sudo apt-get update
          sudo apt-get install gh -y

      - name: Extract JIRA Ticket from Branch
        id: extract_jira
        run: |
          BRANCH_NAME="${{ github.head_ref }}"
          echo "Branch name: $BRANCH_NAME"

          # Extract JIRA ticket number (e.g., ABC-1234)
          JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')

          if [ -z "$JIRA_TICKET" ]; then
            echo "No JIRA ticket found in branch name."
            exit 1
          fi

          echo "JIRA Ticket: $JIRA_TICKET"
          echo "JIRA_TICKET=$JIRA_TICKET" >> $GITHUB_ENV

      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Get Current PR Title
        id: get_pr_title
        run: |
          PR_NUMBER=${{ github.event.pull_request.number }}
          echo "Fetching PR title for PR #$PR_NUMBER"

          # Fetch the current PR title using GitHub CLI
          PR_TITLE=$(gh pr view $PR_NUMBER --json title -q ".title")

          if [ -z "$PR_TITLE" ]; then
            echo "Error fetching PR title."
            exit 1
          fi

          echo "Current PR Title: $PR_TITLE"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Update PR Title
        if: ${{ env.JIRA_TICKET != '' && env.PR_TITLE != '' }}
        run: |
          # Check if the JIRA ticket is already in the title
          if [[ "$PR_TITLE" != *"$JIRA_TICKET"* ]]; then
            UPDATED_TITLE="[$JIRA_TICKET] $PR_TITLE"

            echo "Updating PR title to: $UPDATED_TITLE"

            # Update the PR title using GitHub CLI
            gh pr edit ${{ github.event.pull_request.number }} --title "$UPDATED_TITLE"

            echo "PR title updated successfully."
          else
            echo "JIRA ticket already present in the title."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_TICKET: ${{ env.JIRA_TICKET }}
          PR_TITLE: ${{ env.PR_TITLE }}

