name: Extract Branch Prefix/Add Jira Link

on:
  pull_request:

jobs:
  add_deploy_url:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract Jira Story Number
        id: extract_jira_story_number
        run: |
          # Get the branch name
          branch_name=$(echo "${{ github.head_ref }}")
          echo "Branch Name: $branch_name"

          # Extract Jira story number using regex
          if [[ $branch_name =~ ([^-]+-[^-]+) ]]; then
            jira_story_number="${BASH_REMATCH[1]}"
            echo "Jira Story Number: $jira_story_number"
          else
            jira_story_number=""
            echo "Jira story number not found in branch name"
          fi

          echo "::set-output name=jira_story_number::$jira_story_number"

      - name: Prepend Jira ticket to PR title
        if: env.branch_name
        run: |
          new_title="${{ steps.extract_jira_story_number.outputs.jira_story_number }}: ${{ env.pr_title }}"
          gh pr edit ${{ github.event.pull_request.number }} --title "$new_title"
