name: Prepend JIRA Ticket to PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Extract JIRA Ticket and Update PR Title
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the branch name
          BRANCH_NAME="${{ github.head_ref }}"

          # Extract JIRA ticket number and prefix (assuming format like "feature/ABC-1234-description")
          JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')

          if [ -n "$JIRA_TICKET" ]; then
            # Get the current PR title
            PR_TITLE=$(curl -s \
              -H "Authorization: token $GITHUB_TOKEN" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
              | jq -r .title)

            # Check if the JIRA ticket is already in the title
            if [[ "$PR_TITLE" != *"$JIRA_TICKET"* ]]; then
              # Prepend the JIRA ticket to the title
              UPDATED_TITLE="[$JIRA_TICKET] $PR_TITLE"
              curl -s \
                -X PATCH \
                -H "Authorization: token $GITHUB_TOKEN" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
                -d "{\"title\":\"$UPDATED_TITLE\"}"
            fi
          fi

