name: PR Title

on:
  pull_request:

jobs:
  add_deploy_url:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Extract Jira Story Number
        id: extract_jira_story_number
        run: |
          # Get the branch name
          branch_name=$(echo "${{ github.head_ref }}")
          echo "Branch Name: $branch_name"

          # Extract Jira story number using regex
          if [[ $branch_name =~ ([^-]+-[^-]+) ]]; then
            jira_story_number="${BASH_REMATCH[1]}"
            echo "Jira Story Number: $jira_story_number"
          else
            jira_story_number=""
            echo "Jira story number not found in branch name"
          fi

          echo "::set-output name=jira_story_number::$jira_story_number"
      - name: Add Jira URL to PR title
      - uses: deepakputhraya/action-pr-title@master
        with:
          regex: '([a-z])+\/([a-z])+' # Regex the title should match.
          allowed_prefixes: 'feature,fix,JIRA' # title should start with the given prefix
          disallowed_prefixes: 'feat/,hotfix' # title should not start with the given prefix
          prefix_case_sensitive: false # title prefix are case insensitive
          min_length: 5 # Min length of the title
          max_length: 20 # Max length of the title
          github_token: ${{ secrets.github.token }} # Default: ${{ github.token }}
