name: Prepend JIRA Ticket to PR Title

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Display Branch Name
        id: display-branch
        run: |
          echo "Branch name: ${{ github.head_ref }}"
          echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV

      - name: Extract JIRA Ticket from Branch
        id: extract_jira
        run: |
          BRANCH_NAME="${{ env.BRANCH_NAME }}"
          echo "Extracted Branch Name: $BRANCH_NAME"

          # Extract JIRA ticket number (e.g., ABC-1234)
          JIRA_TICKET=$(echo "$BRANCH_NAME" | grep -oE '[A-Z]+-[0-9]+')

          echo "JIRA Ticket: $JIRA_TICKET"
          echo "JIRA_TICKET=$JIRA_TICKET" >> $GITHUB_ENV

      - name: Debug Environment Variables
        id: debug-variables
        run: |
          echo "JIRA_TICKET=${{ env.JIRA_TICKET }}"
          echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Get PR Title
        id: get_pr_title
        if: ${{ env.JIRA_TICKET != '' }}
        run: |
          echo "Fetching PR Title..."
          PR_TITLE=$(curl -s \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
            | jq -r .title)

          if [ -z "$PR_TITLE" ]; then
            echo "Error fetching PR title."
            exit 1
          fi

          echo "PR Title: $PR_TITLE"
          echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV

      - name: Update PR Title
        if: ${{ env.JIRA_TICKET != '' && env.PR_TITLE != '' }}
        run: |
          # Check if the JIRA ticket is already in the title
          if [[ "$PR_TITLE" != *"$JIRA_TICKET"* ]]; then
            UPDATED_TITLE="[$JIRA_TICKET] $PR_TITLE"

            echo "Updating PR title to: $UPDATED_TITLE"

            curl -s \
              -X PATCH \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }} \
              -d "{\"title\":\"$UPDATED_TITLE\"}"

            echo "PR title updated successfully."
          else
            echo "JIRA ticket already present in the title."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JIRA_TICKET: ${{ env.JIRA_TICKET }}
          PR_TITLE: ${{ env.PR_TITLE }}
